import logging
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from models.requests import ContentRequest
from models.responses import ContentResponse
from services.news_retrieval import get_relevant_articles
from utils.llm import  generate_social_posts
from utils.image_generation import generate_image
from utils.video_generation import generate_video
from utils.meme_generation import generate_meme
from services.vectara import indicizza_documento_vectara, cerca_documenti

# Configura logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)

app = FastAPI(title="PostGenius API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.post("/generate", response_model=ContentResponse)
async def generate_content(req: ContentRequest):
    logger.debug(f"Received request: prompt={req.prompt}, tone={req.tone}, platform={req.platform}")
    try:
        articles = get_relevant_articles(req.prompt, req.tone, req.platform)
        logger.debug(f"Articles retrieved: {articles}")

        if not articles:
            logger.warning("No articles found for the given prompt.")
            return ContentResponse(text="", image="", video="", meme="", sources=[])



        for document in articles:
            try:
                print("\n\n\n\n\n\n\n\n\n\n\n\n",document)
                # Indicizzare il documento con embedding su Vectara
                indicizza_documento_vectara(document)

            except Exception as e:
                print(f"Errore nel processare il documento {document['id']}: {e}")

        summary = cerca_documenti(req.prompt)
        logger.debug(f"Generated summary: {summary}")
        print("\n\n\n\n\n\n\n",summary)

        if not summary:
            logger.warning("No summary generated by LLM.")
            return ContentResponse(text="", image="", video="", meme="", sources=[])

        meme_url = generate_meme(summary)
        logger.debug(f"Generated meme url: {meme_url}")

        # text_post = generate_social_posts(summary, platform=req.platform, tone=req.tone)
        # logger.debug(f"Generated text post: {text_post}")

        # image_url = generate_image(summary)
        # logger.debug(f"Generated image url: {image_url}")

        # video_url = generate_video(summary)
        # logger.debug(f"Generated video url: {video_url}")


        # sources = [art["url"] for art in articles if "url" in art]
        # logger.debug(f"Sources: {sources}")
        logger.debug(f"***FINE***")

        # return ContentResponse(
        #     text=text_post or "",
        #     image=image_url or "",
        #     video=video_url or "",
        #     meme=meme_url or "",
        #     sources=sources
        # )
        return ContentResponse(
            text="",
            image="",
            video="",
            meme="",
            sources=[]
        )
        

    except Exception as e:
        logger.exception(f"Error during content generation: {e}")
        raise HTTPException(status_code=500, detail="Internal server error")
